service: shopify-backend

frameworkVersion: '4'

provider:
  name: aws
  runtime: php-82-fpm
  region: us-west-1
  architecture: arm64
  environment:
    SHOPIFY_ACCESS_TOKEN: ${ssm:/shopify/access_token}
    SHOPIFY_STORE_DOMAIN: ${ssm:/shopify/store_domain}

functions:
  api:
    handler: public/index.php
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - httpApi: '*'

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - tests/**
    - README.md
